item {
  name: "pothole"
  id: 1
  display_name: "pothole"
}
item {
  name: "shadow"
  id: 2
  display_name: "shadow"
}
item {
  name: "crack"
  id: 3
  display_name: "crack"
}
item {
  name: "street-marking"
  id: 4
  display_name: "street-marking"
}
